### PR TITLE
Cleanup Dockerfiles a bit and added Kubernetes Deployment

### PR DESCRIPTION
**Pull request by Zwordi**
Hi,

I would like to add my 2cents to this repository instead of maintaining my own fork.
So:
 - Add the ENV VARIABLES ENV RAILS_SERVE_STATIC_FILES=true to the back in order to have it working (find on latest issue on the pia repository)
 - I made some cleanup on the dockerfiles to try to leverage a bit her sizer
 - Added a Kubernetes folder with instruction about how to deploy pia-back/front into a kubernetes cluster.
I tried to put enough explication on the readme about how to do it.

What do you think ?

### CODE REVIEW

**Comment by gbonnefille** [comment]
Perhaps can you split this contribution in two separated pull-request:
- one for improving Dockerfile (and moving to 2.0.0)
- one for bringing K8S capabilities

**Comment by gbonnefille** [comment]
Oups... seems already done: 866a369b86e1badbecd1cd6016ae822fb564759e

**Comment by Zwordi** [comment]
Seems so :)

**Comment by kosmas58** [comment]
@gbonnefille 

Since Docker released the 2.x version I had issues with kubernetes on my machine.

Now I've installed the lastest Edge release of Docker and kubernetes is running again. 

Now I'm able to approve your changes.

**Comment by kosmas58** [comment]
First created a branch kubernetes. I need some extra time to investigate your stuff. Many thanks for your contribution.

**Comment by gbonnefille** [comment]
> First created a branch kubernetes. I need some extra time to investigate your stuff. Many thanks for your contribution.

Yes, great to create a dedicated branch.

**Comment by Zwordi** [comment]
I'm available for any question event by pm if you need.

**Pull request merged**
